#!/usr/bin/env bash
if [[ "$#" != "1" ]] && [[ "$#" != "2" ]]; then
    echo "Usage: peep <mc ELF executable file>"
    echo "'mc -Op -o foo foo.c' must have been used to compile the executable"
    echo "This command overwrites the executable file with an optimized version"
    exit
fi
PPATH="`dirname \"$0\"`"
if [[ ! -x $PPATH/../squint ]] ;
   then echo "A 'squint' executable must exist.";
   else $ARM_EXEC $PPATH/../squint $1 `readelf -a $1 2>/dev/null | awk '/\.text.*PROGBITS/ { print $6, $7 }'` $2;
fi
